In [1]:
import torch
_ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:840.)
  


In [2]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [3]:
img_t

tensor([[[ 0.0261, -0.8935, -0.6530,  0.9125,  0.7695],
         [ 1.2308,  2.0556, -1.9053, -0.4643, -0.1327],
         [ 0.5952,  0.5019, -2.6810, -1.3640,  0.7656],
         [-0.2562, -0.5585,  0.0041, -1.3368, -0.7997],
         [ 0.6565,  1.2787,  1.7467,  0.1026,  0.4913]],

        [[ 1.0881,  1.3304, -0.4960, -0.4645,  0.9490],
         [-0.8144, -0.9542, -1.9438,  0.0408, -1.0520],
         [ 0.4304,  0.3086,  1.1419,  0.4125,  1.8980],
         [ 0.7122, -0.0409,  0.6538,  0.4201, -0.1624],
         [-0.0141,  0.2679,  0.8204,  0.9317,  1.7264]],

        [[ 0.9318,  0.8612,  0.7804,  1.3869, -0.2214],
         [-1.3084, -0.4868, -1.8530,  0.5281, -1.3851],
         [ 0.4164, -1.0850,  1.0503,  0.5077, -1.5397],
         [-0.5303, -0.2946, -0.8470, -0.0649, -0.6597],
         [ 1.4543, -0.3952,  0.3020, -1.3983, -1.6894]]])

In [4]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [5]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [6]:
batch_t

tensor([[[[ 2.0028, -0.8063, -0.8693,  1.0993,  1.4000],
          [ 1.5443, -0.6458, -0.1557,  0.4078, -0.6063],
          [ 0.0510,  0.5919,  2.5618, -1.7271,  0.5366],
          [ 0.2971, -1.4713, -0.2992,  0.2446, -0.5559],
          [-0.0385,  0.8107, -0.6451, -0.0642, -0.4517]],

         [[ 0.0151, -0.6761,  0.9678, -1.9921,  0.2093],
          [ 1.9165,  0.9147, -0.1620, -1.2440,  0.3902],
          [ 1.0040, -0.4173,  0.8214, -1.5796, -0.3382],
          [-0.6600,  1.3966, -0.3812,  0.2109, -0.7277],
          [-0.8771,  0.0523, -1.2796, -0.6416, -0.0174]],

         [[-0.2050,  0.1281, -0.6888,  0.6382, -1.3818],
          [ 0.2400, -0.9082, -1.9199,  0.4979,  1.2439],
          [-0.7427,  1.6138, -1.8516,  2.0359, -0.6320],
          [ 1.6872,  1.2462, -0.9671, -0.7197, -1.2800],
          [-0.6089, -1.6393,  2.5724, -2.8290,  0.1580]]],


        [[[ 0.3931,  0.4606, -0.4955, -1.3898, -0.6653],
          [ 0.4773,  2.1418,  1.6052, -0.5454, -0.2389],
          [-0.3355,  1.

In [8]:
img_t

tensor([[[ 0.0261, -0.8935, -0.6530,  0.9125,  0.7695],
         [ 1.2308,  2.0556, -1.9053, -0.4643, -0.1327],
         [ 0.5952,  0.5019, -2.6810, -1.3640,  0.7656],
         [-0.2562, -0.5585,  0.0041, -1.3368, -0.7997],
         [ 0.6565,  1.2787,  1.7467,  0.1026,  0.4913]],

        [[ 1.0881,  1.3304, -0.4960, -0.4645,  0.9490],
         [-0.8144, -0.9542, -1.9438,  0.0408, -1.0520],
         [ 0.4304,  0.3086,  1.1419,  0.4125,  1.8980],
         [ 0.7122, -0.0409,  0.6538,  0.4201, -0.1624],
         [-0.0141,  0.2679,  0.8204,  0.9317,  1.7264]],

        [[ 0.9318,  0.8612,  0.7804,  1.3869, -0.2214],
         [-1.3084, -0.4868, -1.8530,  0.5281, -1.3851],
         [ 0.4164, -1.0850,  1.0503,  0.5077, -1.5397],
         [-0.5303, -0.2946, -0.8470, -0.0649, -0.6597],
         [ 1.4543, -0.3952,  0.3020, -1.3983, -1.6894]]])

In [7]:
img_gray_naive = img_t.mean(-3)
img_gray_naive

tensor([[ 0.6820,  0.4327, -0.1229,  0.6117,  0.4991],
        [-0.2973,  0.2049, -1.9007,  0.0349, -0.8566],
        [ 0.4807, -0.0915, -0.1629, -0.1479,  0.3746],
        [-0.0247, -0.2980, -0.0630, -0.3272, -0.5406],
        [ 0.6989,  0.3838,  0.9563, -0.1213,  0.1761]])

In [14]:
img_gray_naive = img_t.mean(-2)
img_gray_naive

tensor([[ 0.4505,  0.4769, -0.6977, -0.4300,  0.2188],
        [ 0.2805,  0.1824,  0.0353,  0.2681,  0.6718],
        [ 0.1927, -0.2801, -0.1135,  0.1919, -1.0991]])

In [15]:
img_gray_naive = img_t.mean(-1)
img_gray_naive

tensor([[ 0.0323,  0.1568, -0.4365, -0.5894,  0.8552],
        [ 0.4814, -0.9447,  0.8383,  0.3166,  0.7465],
        [ 0.7478, -0.9010, -0.1300, -0.4793, -0.3453]])

In [9]:
 img_t.mean()

tensor(0.0232)

In [13]:
batch_gray_naive = batch_t.mean(-3)
batch_gray_naive

tensor([[[ 0.6043, -0.4515, -0.1968, -0.0849,  0.0758],
         [ 1.2336, -0.2131, -0.7459, -0.1128,  0.3426],
         [ 0.1041,  0.5961,  0.5105, -0.4236, -0.1445],
         [ 0.4414,  0.3905, -0.5492, -0.0881, -0.8545],
         [-0.5082, -0.2587,  0.2159, -1.1782, -0.1037]],

        [[-0.5441, -0.3947, -0.0344, -0.4336, -0.0437],
         [ 0.1920,  0.5690,  1.2724, -0.1985,  0.3561],
         [-0.3303,  1.0513, -0.1340, -0.1826, -0.5367],
         [-0.3480,  0.0403,  0.1083,  0.0952, -0.8812],
         [ 0.3007,  0.1339, -0.0342, -0.7684, -1.0688]]])

In [16]:
batch_gray_naive = batch_t.mean(-2)
batch_gray_naive

tensor([[[ 0.7713, -0.3042,  0.1185, -0.0079,  0.0646],
         [ 0.2797,  0.2540, -0.0067, -1.0493, -0.0968],
         [ 0.0741,  0.0881, -0.5710, -0.0754, -0.3784]],

        [[ 0.4769,  1.1446, -0.1476, -0.4646, -1.0539],
         [-0.3663, -0.2376, -0.0388, -0.0983, -0.0999],
         [-0.5484, -0.0671,  0.8933, -0.3298, -0.1507]]])

In [11]:


img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [18]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [20]:
img_t

tensor([[[ 0.0261, -0.8935, -0.6530,  0.9125,  0.7695],
         [ 1.2308,  2.0556, -1.9053, -0.4643, -0.1327],
         [ 0.5952,  0.5019, -2.6810, -1.3640,  0.7656],
         [-0.2562, -0.5585,  0.0041, -1.3368, -0.7997],
         [ 0.6565,  1.2787,  1.7467,  0.1026,  0.4913]],

        [[ 1.0881,  1.3304, -0.4960, -0.4645,  0.9490],
         [-0.8144, -0.9542, -1.9438,  0.0408, -1.0520],
         [ 0.4304,  0.3086,  1.1419,  0.4125,  1.8980],
         [ 0.7122, -0.0409,  0.6538,  0.4201, -0.1624],
         [-0.0141,  0.2679,  0.8204,  0.9317,  1.7264]],

        [[ 0.9318,  0.8612,  0.7804,  1.3869, -0.2214],
         [-1.3084, -0.4868, -1.8530,  0.5281, -1.3851],
         [ 0.4164, -1.0850,  1.0503,  0.5077, -1.5397],
         [-0.5303, -0.2946, -0.8470, -0.0649, -0.6597],
         [ 1.4543, -0.3952,  0.3020, -1.3983, -1.6894]]])

In [19]:
img_weights = (img_t * unsqueezed_weights)
img_weights

tensor([[[ 5.5561e-03, -1.8995e-01, -1.3882e-01,  1.9400e-01,  1.6360e-01],
         [ 2.6167e-01,  4.3703e-01, -4.0507e-01, -9.8717e-02, -2.8219e-02],
         [ 1.2655e-01,  1.0670e-01, -5.6998e-01, -2.8999e-01,  1.6277e-01],
         [-5.4462e-02, -1.1874e-01,  8.7053e-04, -2.8421e-01, -1.7001e-01],
         [ 1.3958e-01,  2.7185e-01,  3.7134e-01,  2.1814e-02,  1.0446e-01]],

        [[ 7.7823e-01,  9.5154e-01, -3.5477e-01, -3.3218e-01,  6.7876e-01],
         [-5.8243e-01, -6.8243e-01, -1.3902e+00,  2.9188e-02, -7.5238e-01],
         [ 3.0783e-01,  2.2073e-01,  8.1672e-01,  2.9500e-01,  1.3574e+00],
         [ 5.0940e-01, -2.9235e-02,  4.6759e-01,  3.0043e-01, -1.1614e-01],
         [-1.0068e-02,  1.9162e-01,  5.8674e-01,  6.6633e-01,  1.2347e+00]],

        [[ 6.7274e-02,  6.2180e-02,  5.6344e-02,  1.0014e-01, -1.5982e-02],
         [-9.4468e-02, -3.5148e-02, -1.3379e-01,  3.8132e-02, -1.0001e-01],
         [ 3.0065e-02, -7.8336e-02,  7.5832e-02,  3.6656e-02, -1.1116e-01],
        

In [22]:
img_gray_weighted = img_weights.sum(-3)
img_gray_weighted

tensor([[ 0.8511,  0.8238, -0.4373, -0.0380,  0.8264],
        [-0.4152, -0.2806, -1.9291, -0.0314, -0.8806],
        [ 0.4644,  0.2491,  0.3226,  0.0417,  1.4090],
        [ 0.4167, -0.1692,  0.4073,  0.0115, -0.3338],
        [ 0.2345,  0.4349,  0.9799,  0.5872,  1.2172]])

In [21]:
batch_weights = (batch_t * unsqueezed_weights)
batch_weights

tensor([[[[ 0.4258, -0.1714, -0.1848,  0.2337,  0.2976],
          [ 0.3283, -0.1373, -0.0331,  0.0867, -0.1289],
          [ 0.0108,  0.1258,  0.5446, -0.3672,  0.1141],
          [ 0.0632, -0.3128, -0.0636,  0.0520, -0.1182],
          [-0.0082,  0.1724, -0.1371, -0.0136, -0.0960]],

         [[ 0.0108, -0.4836,  0.6922, -1.4248,  0.1497],
          [ 1.3707,  0.6542, -0.1159, -0.8897,  0.2791],
          [ 0.7181, -0.2985,  0.5875, -1.1298, -0.2419],
          [-0.4721,  0.9989, -0.2726,  0.1508, -0.5205],
          [-0.6273,  0.0374, -0.9152, -0.4589, -0.0124]],

         [[-0.0148,  0.0092, -0.0497,  0.0461, -0.0998],
          [ 0.0173, -0.0656, -0.1386,  0.0359,  0.0898],
          [-0.0536,  0.1165, -0.1337,  0.1470, -0.0456],
          [ 0.1218,  0.0900, -0.0698, -0.0520, -0.0924],
          [-0.0440, -0.1184,  0.1857, -0.2043,  0.0114]]],


        [[[ 0.0836,  0.0979, -0.1053, -0.2955, -0.1414],
          [ 0.1015,  0.4553,  0.3413, -0.1160, -0.0508],
          [-0.0713,  0.

In [23]:
batch_gray_weighted = batch_weights.sum(-3)
batch_gray_weighted

tensor([[[ 0.4218, -0.6458,  0.4576, -1.1450,  0.3476],
         [ 1.7163,  0.4513, -0.2876, -0.7670,  0.2400],
         [ 0.6753, -0.0561,  0.9984, -1.3500, -0.1734],
         [-0.2871,  0.7760, -0.4060,  0.1509, -0.7311],
         [-0.6795,  0.0914, -0.8666, -0.6768, -0.0971]],

        [[-0.4921, -0.4492, -0.7540,  0.0669, -1.0038],
         [ 0.5351,  0.5061,  1.3111, -0.3265,  0.7239],
         [-0.9055,  1.1284, -0.5597, -0.2169,  0.4196],
         [-0.1811, -0.7837,  0.5199,  0.5785, -0.8648],
         [ 0.0427, -0.0589, -0.4906, -1.0665, -0.8070]]])

In [25]:
batch_gray_weighted.shape

torch.Size([2, 5, 5])

In [24]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [26]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
img_gray_weighted_fancy

tensor([[ 0.8511,  0.8238, -0.4373, -0.0380,  0.8264],
        [-0.4152, -0.2806, -1.9291, -0.0314, -0.8806],
        [ 0.4644,  0.2491,  0.3226,  0.0417,  1.4090],
        [ 0.4167, -0.1692,  0.4073,  0.0115, -0.3338],
        [ 0.2345,  0.4349,  0.9799,  0.5872,  1.2172]])

In [ ]:

batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [27]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [29]:
weights_named.shape

torch.Size([3])

In [28]:
img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [30]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [31]:
weights_aligned

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]], names=('channels', 'rows', 'columns'))

In [32]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [33]:
gray_named

tensor([[ 0.8511,  0.8238, -0.4373, -0.0380,  0.8264],
        [-0.4152, -0.2806, -1.9291, -0.0314, -0.8806],
        [ 0.4644,  0.2491,  0.3226,  0.0417,  1.4090],
        [ 0.4167, -0.1692,  0.4073,  0.0115, -0.3338],
        [ 0.2345,  0.4349,  0.9799,  0.5872,  1.2172]],
       names=('rows', 'columns'))

In [ ]:
try:
    gray_named = (img_named[..., :3] * weights_named).sum('channels')
except Exception as e:
    print(e)

Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.


In [ ]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))