In [1]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, threshold=50)

In [2]:
!git clone https://github.com/duybluemind1988/dlwpt-code

In [3]:
import os 
os.getcwd()

'/content'

In [4]:
#!apt-get update

In [5]:
import imageio

In [6]:
img_arr = imageio.imread('https://github.com/duybluemind1988/dlwpt-code/blob/master/data/p1ch4/image-dog/bobby.jpg?raw=true')
img_arr.shape

(720, 1280, 3)

In [7]:
img = torch.from_numpy(img_arr)
out = img.permute(2, 0, 1)

In [8]:
img.shape

torch.Size([720, 1280, 3])

The only thing to watch out for is the layout of the dimensions.
PyTorch modules dealing with image data require tensors to be laid out as C × H × W :
channels, height, and width, respectively.

In [9]:
out.shape

torch.Size([3, 720, 1280])

In [31]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

In [32]:
import os

data_dir = '/content/dlwpt-code/data/p1ch4/image-cats/'
filenames = [name for name in os.listdir(data_dir)
             if os.path.splitext(name)[-1] == '.png']
filenames

['cat3.png', 'cat2.png', 'cat1.png']

In [33]:
for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    print(img_t.shape)
    img_t = img_t.permute(2, 0, 1)
    print(img_t.shape)
    img_t = img_t[:3] # <1>
    print(img_t.shape)
    batch[i] = img_t
    print(batch[i])

torch.Size([256, 256, 3])
torch.Size([3, 256, 256])
torch.Size([3, 256, 256])
tensor([[[238, 238,  ..., 215, 215],
         [238, 238,  ..., 215, 215],
         ...,
         [214, 213,  ..., 190, 192],
         [214, 213,  ..., 190, 192]],

        [[195, 195,  ..., 175, 175],
         [195, 195,  ..., 175, 175],
         ...,
         [128, 127,  ..., 103, 105],
         [128, 127,  ..., 103, 105]],

        [[137, 137,  ..., 126, 126],
         [137, 137,  ..., 126, 126],
         ...,
         [ 79,  78,  ...,  69,  71],
         [ 79,  78,  ...,  69,  72]]], dtype=torch.uint8)
torch.Size([256, 256, 3])
torch.Size([3, 256, 256])
torch.Size([3, 256, 256])
tensor([[[202, 193,  ...,  13,  12],
         [199, 192,  ...,  14,  14],
         ...,
         [ 75,  68,  ...,  36,  37],
         [ 85, 103,  ...,  37,  38]],

        [[151, 139,  ...,   9,   8],
         [151, 140,  ...,  11,  11],
         ...,
         [ 33,  26,  ...,  26,  27],
         [ 40,  58,  ...,  27,  28]],

     

In [34]:
batch = batch.float()
batch /= 255.0
batch

tensor([[[[0.9333, 0.9333,  ..., 0.8431, 0.8431],
          [0.9333, 0.9333,  ..., 0.8431, 0.8431],
          ...,
          [0.8392, 0.8353,  ..., 0.7451, 0.7529],
          [0.8392, 0.8353,  ..., 0.7451, 0.7529]],

         [[0.7647, 0.7647,  ..., 0.6863, 0.6863],
          [0.7647, 0.7647,  ..., 0.6863, 0.6863],
          ...,
          [0.5020, 0.4980,  ..., 0.4039, 0.4118],
          [0.5020, 0.4980,  ..., 0.4039, 0.4118]],

         [[0.5373, 0.5373,  ..., 0.4941, 0.4941],
          [0.5373, 0.5373,  ..., 0.4941, 0.4941],
          ...,
          [0.3098, 0.3059,  ..., 0.2706, 0.2784],
          [0.3098, 0.3059,  ..., 0.2706, 0.2824]]],


        [[[0.7922, 0.7569,  ..., 0.0510, 0.0471],
          [0.7804, 0.7529,  ..., 0.0549, 0.0549],
          ...,
          [0.2941, 0.2667,  ..., 0.1412, 0.1451],
          [0.3333, 0.4039,  ..., 0.1451, 0.1490]],

         [[0.5922, 0.5451,  ..., 0.0353, 0.0314],
          [0.5922, 0.5490,  ..., 0.0431, 0.0431],
          ...,
          [0.12

In [35]:
batch.shape

torch.Size([3, 3, 256, 256])

In [36]:
n_channels = batch.shape[1]
n_channels

3

In [37]:
batch[:, 1].shape

torch.Size([3, 256, 256])

In [38]:
batch[:, 2].shape

torch.Size([3, 256, 256])

In [39]:
batch[:, 1]

tensor([[[0.7647, 0.7647,  ..., 0.6863, 0.6863],
         [0.7647, 0.7647,  ..., 0.6863, 0.6863],
         ...,
         [0.5020, 0.4980,  ..., 0.4039, 0.4118],
         [0.5020, 0.4980,  ..., 0.4039, 0.4118]],

        [[0.5922, 0.5451,  ..., 0.0353, 0.0314],
         [0.5922, 0.5490,  ..., 0.0431, 0.0431],
         ...,
         [0.1294, 0.1020,  ..., 0.1020, 0.1059],
         [0.1569, 0.2275,  ..., 0.1059, 0.1098]],

        [[0.5451, 0.5294,  ..., 0.5294, 0.5765],
         [0.6275, 0.4667,  ..., 0.4784, 0.4863],
         ...,
         [0.4353, 0.4353,  ..., 0.4392, 0.4118],
         [0.4353, 0.4078,  ..., 0.4314, 0.4353]]])

In [40]:
for c in range(n_channels):
    mean = torch.mean(batch[:, c])
    std = torch.std(batch[:, c])
    batch[:, c] = (batch[:, c] - mean) / std

In [41]:
mean

tensor(0.3554)

In [42]:
std

tensor(0.1931)

In [43]:
batch[:,1]

tensor([[[ 1.5253,  1.5253,  ...,  1.1460,  1.1460],
         [ 1.5253,  1.5253,  ...,  1.1460,  1.1460],
         ...,
         [ 0.2546,  0.2356,  ..., -0.2196, -0.1816],
         [ 0.2546,  0.2356,  ..., -0.2196, -0.1816]],

        [[ 0.6908,  0.4632,  ..., -2.0024, -2.0214],
         [ 0.6908,  0.4822,  ..., -1.9645, -1.9645],
         ...,
         [-1.5472, -1.6800,  ..., -1.6800, -1.6610],
         [-1.4144, -1.0731,  ..., -1.6610, -1.6420]],

        [[ 0.4632,  0.3874,  ...,  0.3874,  0.6149],
         [ 0.8615,  0.0839,  ...,  0.1408,  0.1787],
         ...,
         [-0.0678, -0.0678,  ..., -0.0489, -0.1816],
         [-0.0678, -0.2006,  ..., -0.0868, -0.0678]]])